@extends('layouts.app')

@section('title', $report['name'])
@section('page-title', $report['name'])
@section('page-description', 'Generated on ' . $report['generated_at']->format('M j, Y g:i A'))

@push('styles')
<style>
    .report-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border-radius: 15px;
        padding: 2rem;
        margin-bottom: 2rem;
    }
    
    .metric-card {
        background: white;
        border-radius: 10px;
        padding: 1.5rem;
        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        text-align: center;
        height: 100%;
    }
    
    .metric-number {
        font-size: 2.5rem;
        font-weight: 800;
        margin-bottom: 0.5rem;
    }
    
    .data-table {
        background: white;
        border-radius: 10px;
        overflow: hidden;
        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    
    .chart-container {
        background: white;
        border-radius: 10px;
        padding: 1.5rem;
        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        margin-bottom: 2rem;
    }
</style>
@endpush

@section('content')
<div class="container-fluid">
    <!-- Report Header -->
    <div class="report-header">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h1 class="mb-2">{{ $report['name'] }}</h1>
                <p class="mb-0 opacity-75">
                    Generated on {{ $report['generated_at']->format('F j, Y \a\t g:i A') }} • 
                    Report Type: {{ ucwords(str_replace('-', ' ', $report['type'])) }}
                </p>
            </div>
            <div class="col-md-4 text-end">
                <div class="btn-group">
                    <button class="btn btn-light" onclick="window.print()">
                        <i class="fas fa-print me-2"></i>Print
                    </button>
                    <a href="{{ route('admin.reports.download', $report['id']) }}" class="btn btn-success">
                        <i class="fas fa-download me-2"></i>Download {{ strtoupper($report['format']) }}
                    </a>
                    <a href="{{ route('admin.reports.index') }}" class="btn btn-outline-light">
                        <i class="fas fa-arrow-left me-2"></i>Back to Reports
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Report Content -->
    @if($report['type'] === 'revenue-analysis')
        @include('admin.reports.types.revenue-analysis', ['data' => $report['data']])
    @elseif($report['type'] === 'shop-performance')
        @include('admin.reports.types.shop-performance', ['data' => $report['data']])
    @elseif($report['type'] === 'customer-insights')
        @include('admin.reports.types.customer-insights', ['data' => $report['data']])
    @elseif($report['type'] === 'geographic-analysis')
        @include('admin.reports.types.geographic-analysis', ['data' => $report['data']])
    @else
        <div class="card">
            <div class="card-body">
                <div class="text-center py-5">
                    <i class="fas fa-file-alt text-muted mb-3" style="font-size: 4rem;"></i>
                    <h4 class="text-muted mb-3">Report Generated Successfully</h4>
                    <p class="text-muted mb-4">
                        This {{ ucwords(str_replace('-', ' ', $report['type'])) }} report contains detailed analysis 
                        and insights based on your selected criteria.
                    </p>
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <tr>
                                    <td class="fw-bold">Report Type:</td>
                                    <td>{{ ucwords(str_replace('-', ' ', $report['type'])) }}</td>
                                </tr>
                                <tr>
                                    <td class="fw-bold">Format:</td>
                                    <td>{{ strtoupper($report['format']) }}</td>
                                </tr>
                                <tr>
                                    <td class="fw-bold">Generated:</td>
                                    <td>{{ $report['generated_at']->format('M j, Y g:i A') }}</td>
                                </tr>
                                <tr>
                                    <td class="fw-bold">Generated By:</td>
                                    <td>{{ $report['generated_by'] }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif
</div>
@endsection