<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Receipt Portal Login – M-Right Anti-Theft</title>
    <meta name="description" content="Access your Phone Anti-Theft Digital Receipt portal to manage your device registration.">
    <link href="https://fonts.bunny.net/css?family=inter:400,500,600,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        :root { --primary: #C0392B; --primary-dark: #96281B; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', sans-serif; background: linear-gradient(135deg, #C0392B 0%, #96281B 40%, #1A252F 100%); min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 1rem; }
        .login-card { background: white; border-radius: 24px; padding: 2.5rem; width: 100%; max-width: 420px; box-shadow: 0 20px 60px rgba(0,0,0,0.3); }
        .brand { text-align: center; margin-bottom: 2rem; }
        .brand-icon { width: 64px; height: 64px; background: linear-gradient(135deg, var(--primary), var(--primary-dark)); border-radius: 16px; display: flex; align-items: center; justify-content: center; margin: 0 auto 1rem; }
        .brand-title { font-size: 1.3rem; font-weight: 800; color: #1A252F; }
        .brand-sub { font-size: 0.8rem; color: #7F8C8D; margin-top: 0.25rem; }
        .form-label-custom { font-weight: 600; font-size: 0.85rem; color: #2C3E50; text-transform: uppercase; letter-spacing: 0.5px; }
        .form-control-custom { border: 2px solid #E8ECEF; border-radius: 12px; padding: 0.85rem 1rem; font-size: 1rem; transition: all 0.2s; }
        .form-control-custom:focus { border-color: var(--primary); box-shadow: 0 0 0 4px rgba(192,57,43,0.1); outline: none; }
        .btn-login { background: linear-gradient(135deg, var(--primary), var(--primary-dark)); color: white; border: none; border-radius: 12px; padding: 0.9rem; font-size: 1rem; font-weight: 700; width: 100%; cursor: pointer; transition: all 0.3s; }
        .btn-login:hover { transform: translateY(-2px); box-shadow: 0 8px 24px rgba(192,57,43,0.4); }
        .help-box { background: #F8FAFC; border-radius: 12px; padding: 1rem; font-size: 0.82rem; color: #7F8C8D; border: 1px solid #E8ECEF; margin-top: 1.5rem; }
        .back-link { text-align: center; margin-top: 1.5rem; font-size: 0.875rem; }
        .back-link a { color: #7F8C8D; text-decoration: none; }
        .back-link a:hover { color: var(--primary); }
    </style>
</head>
<body>
    <div class="login-card">
        <div class="brand">
            <div class="brand-icon">
                <i class="fas fa-shield-halved" style="font-size:1.8rem;color:white;"></i>
            </div>
            <div class="brand-title">Receipt Portal</div>
            <div class="brand-sub">M-Right Phone Anti-Theft Digital Receipt</div>
        </div>

        @if (session('success'))
            <div class="alert alert-success py-2 small rounded-3 mb-3">{{ session('success') }}</div>
        @endif

        @if ($errors->any())
            <div class="alert alert-danger py-2 small rounded-3 mb-3">{{ $errors->first() }}</div>
        @endif

        <form method="POST" action="{{ route('receipt.portal.login.post') }}">
            @csrf
            <div class="mb-3">
                <label class="form-label-custom mb-2 d-block">Phone Number</label>
                <input type="tel" name="phone_number" class="form-control-custom" placeholder="e.g. 08012345678" value="{{ old('phone_number') }}" required>
            </div>
            <div class="mb-4">
                <label class="form-label-custom mb-2 d-block">Resale PIN</label>
                <input type="password" name="resale_pin" class="form-control-custom" placeholder="6-digit PIN from your receipt" maxlength="6" required>
            </div>
            <button type="submit" class="btn-login">
                <i class="fas fa-sign-in-alt me-2"></i> Access My Receipt Portal
            </button>
        </form>

        <div class="help-box">
            <strong>Where is my Resale PIN?</strong><br>
            Your 6-digit Resale PIN is printed on your <strong>Phone Anti-Theft Digital Receipt</strong> generated by the phone shop where you purchased your device. Check the receipt PDF or printout.
        </div>

        <div class="back-link">
            <a href="{{ route('home') }}"><i class="fas fa-arrow-left me-1"></i> Back to Homepage</a>
        </div>
    </div>
</body>
</html>
